name: sync to S3

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Actualiza a la versión 4

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # Configura Java 17
        with:
          distribution: 'temurin'  # Especifica la distribución de JDK
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean previous artifacts
        run: rm -rf target/*.jar

      - name: Build with Maven
        run: mvn clean compile package -DskipTests  # Ejecuta comandos Maven para compilar y empaquetar

      - name: List target directory
        run: ls -l target/  # Verifica que el archivo JAR está presente

      - name: Upload JAR to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'target'  # Directorio de origen donde se encuentra el archivo JAR
          DEST_DIR: '/'  
